function F_star_10el = ekf_F_10el_rect(in1)
%ekf_F_10el_rect
%    F_star_10el = ekf_F_10el_rect(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Sep-2025 16:38:35

dt = in1(23,:);
q1 = in1(4,:);
q2 = in1(5,:);
q3 = in1(6,:);
q4 = in1(7,:);
u_a_new1 = in1(14,:);
u_a_new2 = in1(15,:);
u_a_new3 = in1(16,:);
u_g_new1 = in1(11,:);
u_g_new2 = in1(12,:);
u_g_new3 = in1(13,:);
w_a1 = in1(20,:);
w_a2 = in1(21,:);
w_a3 = in1(22,:);
w_g1 = in1(17,:);
w_g2 = in1(18,:);
w_g3 = in1(19,:);
mt1 = [1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,dt.*(u_g_new1./2.0+w_g1./2.0),dt.*(u_g_new2./2.0+w_g2./2.0),dt.*(u_g_new3./2.0+w_g3./2.0),-dt.*(q4.*(u_a_new2+w_a2).*2.0-q3.*(u_a_new3+w_a3).*2.0),dt.*(q4.*(u_a_new1+w_a1).*2.0-q2.*(u_a_new3+w_a3).*2.0),-dt.*(q3.*(u_a_new1+w_a1).*2.0-q2.*(u_a_new2+w_a2).*2.0),0.0,0.0,0.0,-dt.*(u_g_new1./2.0+w_g1./2.0),1.0,-dt.*(u_g_new3./2.0+w_g3./2.0),dt.*(u_g_new2./2.0+w_g2./2.0),dt.*(q3.*(u_a_new2+w_a2).*2.0+q4.*(u_a_new3+w_a3).*2.0)];
mt2 = [-dt.*(q3.*(u_a_new1+w_a1).*-2.0+q2.*(u_a_new2+w_a2).*4.0+q1.*(u_a_new3+w_a3).*2.0),dt.*(q1.*(u_a_new2+w_a2).*2.0+q4.*(u_a_new1+w_a1).*2.0-q2.*(u_a_new3+w_a3).*4.0),0.0,0.0,0.0,-dt.*(u_g_new2./2.0+w_g2./2.0),dt.*(u_g_new3./2.0+w_g3./2.0),1.0,-dt.*(u_g_new1./2.0+w_g1./2.0),dt.*(q3.*(u_a_new1+w_a1).*-4.0+q2.*(u_a_new2+w_a2).*2.0+q1.*(u_a_new3+w_a3).*2.0),dt.*(q2.*(u_a_new1+w_a1).*2.0+q4.*(u_a_new3+w_a3).*2.0),-dt.*(q1.*(u_a_new1+w_a1).*2.0-q4.*(u_a_new2+w_a2).*2.0+q3.*(u_a_new3+w_a3).*4.0),0.0,0.0,0.0,-dt.*(u_g_new3./2.0+w_g3./2.0),-dt.*(u_g_new2./2.0+w_g2./2.0),dt.*(u_g_new1./2.0+w_g1./2.0)];
mt3 = [1.0,-dt.*(q1.*(u_a_new2+w_a2).*2.0+q4.*(u_a_new1+w_a1).*4.0-q2.*(u_a_new3+w_a3).*2.0),dt.*(q1.*(u_a_new1+w_a1).*2.0-q4.*(u_a_new2+w_a2).*4.0+q3.*(u_a_new3+w_a3).*2.0),dt.*(q2.*(u_a_new1+w_a1).*2.0+q3.*(u_a_new2+w_a2).*2.0),dt,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,dt,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,dt,0.0,0.0,0.0,0.0,0.0,0.0,1.0];
F_star_10el = reshape([mt1,mt2,mt3],10,10);
end
