function x_new_10el = ekf_processModel_10el_rect(in1)
%ekf_processModel_10el_rect
%    X_NEW_10EL = ekf_processModel_10el_rect(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Sep-2025 16:38:35

dt = in1(23,:);
p1 = in1(1,:);
p2 = in1(2,:);
p3 = in1(3,:);
q1 = in1(4,:);
q2 = in1(5,:);
q3 = in1(6,:);
q4 = in1(7,:);
u_a_new1 = in1(14,:);
u_a_new2 = in1(15,:);
u_a_new3 = in1(16,:);
u_g_new1 = in1(11,:);
u_g_new2 = in1(12,:);
u_g_new3 = in1(13,:);
v1 = in1(8,:);
v2 = in1(9,:);
v3 = in1(10,:);
w_a1 = in1(20,:);
w_a2 = in1(21,:);
w_a3 = in1(22,:);
w_g1 = in1(17,:);
w_g2 = in1(18,:);
w_g3 = in1(19,:);
mt1 = [p1+dt.*v1;p2+dt.*v2;p3+dt.*v3;q1-dt.*((q2.*(u_g_new1+w_g1))./2.0+(q3.*(u_g_new2+w_g2))./2.0+(q4.*(u_g_new3+w_g3))./2.0);q2+dt.*((q1.*(u_g_new1+w_g1))./2.0-(q4.*(u_g_new2+w_g2))./2.0+(q3.*(u_g_new3+w_g3))./2.0);q3+dt.*((q1.*(u_g_new2+w_g2))./2.0+(q4.*(u_g_new1+w_g1))./2.0-(q2.*(u_g_new3+w_g3))./2.0);q4+dt.*(q3.*(u_g_new1+w_g1).*(-1.0./2.0)+(q2.*(u_g_new2+w_g2))./2.0+(q1.*(u_g_new3+w_g3))./2.0);v1-dt.*((u_a_new1+w_a1).*(q3.^2.*2.0+q4.^2.*2.0-1.0)+(u_a_new2+w_a2).*(q1.*q4.*2.0-q2.*q3.*2.0)-(u_a_new3+w_a3).*(q1.*q3.*2.0+q2.*q4.*2.0))];
mt2 = [v2-dt.*((u_a_new2+w_a2).*(q2.^2.*2.0+q4.^2.*2.0-1.0)-(u_a_new1+w_a1).*(q1.*q4.*2.0+q2.*q3.*2.0)+(u_a_new3+w_a3).*(q1.*q2.*2.0-q3.*q4.*2.0));v3-dt.*((u_a_new3+w_a3).*(q2.^2.*2.0+q3.^2.*2.0-1.0)+(u_a_new1+w_a1).*(q1.*q3.*2.0-q2.*q4.*2.0)-(u_a_new2+w_a2).*(q1.*q2.*2.0+q3.*q4.*2.0)-9.81e+2./1.0e+2)];
x_new_10el = [mt1;mt2];
end
