function x_new_16el = ekf_processModel_16el_rect(in1)
%ekf_processModel_16el_rect
%    X_NEW_16EL = ekf_processModel_16el_rect(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    19-Sep-2025 16:38:35

ba1 = in1(11,:);
ba2 = in1(12,:);
ba3 = in1(13,:);
bg1 = in1(14,:);
bg2 = in1(15,:);
bg3 = in1(16,:);
dt = in1(35,:);
p1 = in1(1,:);
p2 = in1(2,:);
p3 = in1(3,:);
q1 = in1(4,:);
q2 = in1(5,:);
q3 = in1(6,:);
q4 = in1(7,:);
u_a_new1 = in1(20,:);
u_a_new2 = in1(21,:);
u_a_new3 = in1(22,:);
u_g_new1 = in1(17,:);
u_g_new2 = in1(18,:);
u_g_new3 = in1(19,:);
v1 = in1(8,:);
v2 = in1(9,:);
v3 = in1(10,:);
w_a1 = in1(26,:);
w_a2 = in1(27,:);
w_a3 = in1(28,:);
w_ba1 = in1(29,:);
w_ba2 = in1(30,:);
w_ba3 = in1(31,:);
w_bg1 = in1(32,:);
w_bg2 = in1(33,:);
w_bg3 = in1(34,:);
w_g1 = in1(23,:);
w_g2 = in1(24,:);
w_g3 = in1(25,:);
mt1 = [p1+dt.*v1;p2+dt.*v2;p3+dt.*v3;q1-dt.*((q2.*(-bg1+u_g_new1+w_g1))./2.0+(q3.*(-bg2+u_g_new2+w_g2))./2.0+(q4.*(-bg3+u_g_new3+w_g3))./2.0);q2+dt.*((q1.*(-bg1+u_g_new1+w_g1))./2.0-(q4.*(-bg2+u_g_new2+w_g2))./2.0+(q3.*(-bg3+u_g_new3+w_g3))./2.0);q3+dt.*((q1.*(-bg2+u_g_new2+w_g2))./2.0+(q4.*(-bg1+u_g_new1+w_g1))./2.0-(q2.*(-bg3+u_g_new3+w_g3))./2.0);q4+dt.*(q3.*(-bg1+u_g_new1+w_g1).*(-1.0./2.0)+(q2.*(-bg2+u_g_new2+w_g2))./2.0+(q1.*(-bg3+u_g_new3+w_g3))./2.0)];
mt2 = [v1-dt.*((-ba1+u_a_new1+w_a1).*(q3.^2.*2.0+q4.^2.*2.0-1.0)+(q1.*q4.*2.0-q2.*q3.*2.0).*(-ba2+u_a_new2+w_a2)-(q1.*q3.*2.0+q2.*q4.*2.0).*(-ba3+u_a_new3+w_a3));v2-dt.*((-ba2+u_a_new2+w_a2).*(q2.^2.*2.0+q4.^2.*2.0-1.0)-(q1.*q4.*2.0+q2.*q3.*2.0).*(-ba1+u_a_new1+w_a1)+(q1.*q2.*2.0-q3.*q4.*2.0).*(-ba3+u_a_new3+w_a3))];
mt3 = [v3-dt.*((-ba3+u_a_new3+w_a3).*(q2.^2.*2.0+q3.^2.*2.0-1.0)+(q1.*q3.*2.0-q2.*q4.*2.0).*(-ba1+u_a_new1+w_a1)-(q1.*q2.*2.0+q3.*q4.*2.0).*(-ba2+u_a_new2+w_a2)-9.81e+2./1.0e+2);ba1+dt.*w_ba1;ba2+dt.*w_ba2;ba3+dt.*w_ba3;bg1+dt.*w_bg1;bg2+dt.*w_bg2;bg3+dt.*w_bg3];
x_new_16el = [mt1;mt2;mt3];
end
